import AddPost from './AddPost'
import Home from './Home'
import Post from './Post'
import EditedPost from './EditedPost'
import Login from './Login'
import Signup from './Signup'
import AllPost from './AllPost'
import PasswordReset  from './PasswordReset'
import CreatePasswordRecovery from './CreatePasswordRecovery'
import MyPost from './MyPost'
export {AddPost, MyPost, Home, PasswordReset, Post, EditedPost, Login, Signup, AllPost, CreatePasswordRecovery}